name: publish

on:
    push:
        branches:
            - master
        tags:
            - 'v*'

env:
    SOLUTION_NAME: 'Wox-EasyHelper.sln' # set this to your application's name

jobs:
    build:
        name: Build and deploy
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: "Set env vars"
              run: |
                  # REFNAME : the version number if it's a tag, or the branch name if it's a branch
                  echo|set /p="REFNAME=" >> "%GITHUB_ENV%"
                  echo ${{ github.ref }} | scripts\sed.exe -e "s/tags\/v/tags\//; s/.*\///" >> "%GITHUB_ENV%"

            - name: Restore NuGet packages
              run: nuget restore ${{ env.SOLUTION_NAME }}

            - name: Build
              run: scripts\compile.cmd
      
            - name: Create package (dev)
              if: "!contains(github.ref, 'refs/tags')"
              run: scripts\create-package.cmd "dev"

            - name: Create package (release ${{ env.REFNAME }})
              if: "contains(github.ref, 'refs/tags')"
              run: scripts\create-package.cmd ${{ env.REFNAME }} ${{ secrets.NUGET_API_KEY }}

            - name: List directory
              run: dir

            - name: Publish artifacts
              uses: actions/upload-artifact@v2
              with:
                name: Wox.EasyHelper
                path: Wox.EasyHelper.*.nupkg
