name: build and publish

on:
    push:
        branches:
            - '*'
        tags:
            - 'v*'

env:
    BASE_SOLUTION_NAME: 'BarLauncher-EasyHelper'

jobs:
    build:
        name: Build and deploy
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Get the version (for tags)
              if: "startsWith(github.ref, 'refs/tags')"
              shell: bash
              run: echo "VERSION=$(cat VERSION)" >> "${GITHUB_ENV}"

            - name: Get the version (for normal commits)
              if: "!startsWith(github.ref, 'refs/tags')"
              shell: bash
              run: echo "VERSION=$(cat VERSION)-$(date +%s)" >> "${GITHUB_ENV}"

            - name: pack ${{ env.BASE_SOLUTION_NAME }} (version ${{ env.VERSION }})
              run: dotnet pack ${{ env.BASE_SOLUTION_NAME }}.sln -c Release -p:VERSION=${{ env.VERSION }}

            - name: Upload Artifacts (version ${{ env.VERSION }})
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.BASE_SOLUTION_NAME }}-${{ env.VERSION }}
                  path: ./nupkg/*.nupkg

            - name: Publish to api.nuget.org
              if: "success() && startsWith(github.ref, 'refs/tags')"
              run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

            - name: "Create release ${{ env.VERSION }}"
              if: "success() && startsWith(github.ref, 'refs/tags')"
              uses: "softprops/action-gh-release@v1"
              with:
                  files: ./nupkg/*.nupkg
                  draft: false
                  prerelease: false
