name: build and publish

on:
    push:
        branches:
            - master
        tags:
            - 'v*'

env:
    SOLUTION_NAME: 'BarLauncher-EasyHelper.sln' # set this to your application's name

jobs:
    build:
        name: Build and deploy
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: build ${{ env.SOLUTION_NAME }}
              run: dotnet.exe build ${{ env.SOLUTION_NAME }}

            - name: pack ${{ env.SOLUTION_NAME }}
              run: dotnet.exe pack ${{ env.SOLUTION_NAME }}

            - name: Upload Artifacts
              if: "contains(github.ref, 'refs/tags')"
              uses: actions/upload-artifact@v2
              with:
                name: nupkg
                path: ./nupkg/*.nupkg

            - name: Publish to api.nuget.org
              if: "contains(github.ref, 'refs/tags')"
              run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

            - name: List directory nupkg
              run: dir nupkg
